### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by mengyingWU** [nicegdhj/GoDeepLearning#1]
您好，我是深度学习刚入门同时也想尝试搭建一个神经网络，请问我可以加入你吗，另外我推荐了一些学习的教程希望你可以采纳

**Comment by nicegdhj** [comment]
我是准备在三月份之前用TF或者参照tf自己写一个类似做车牌识别这种分类的网络吧，最近一直断断续续的 ...

**Comment by nicegdhj** [comment]
我是准备在三月份之前用TF或者参照tf自己写一个类似做车牌识别这种分类的网络吧，最近一直断断续续的 ...

**Comment by nicegdhj** [comment]
我是准备在三月份之前用TF或者参照tf自己写一个类似做车牌识别这种分类的网络吧，最近一直断断续续的 ...

**Comment by mengyingWU** [comment]
这段时间刚好我做了一个keras框架下的手写数字识别，可能对你有帮助

**Comment by nicegdhj** [comment]
谢谢分享，我也是入门不久，共同学习吧

**Comment by mengyingWU** [comment]
我也是刚跟着国外的老师做半监督学习 但是都是法语的 语言不太通 想找一些人一起研究

**Comment by nicegdhj** [comment]
可以啊 加个微信什么 或者群 什么的

**Comment by mengyingWU** [comment]
我在github上找了好久，并没有找到交流群

**Comment by nicegdhj** [comment]
gd438499123我微信 github上交谈什么的不太熟悉不方便

**Comment by aureosun** [comment]
您好，我想用TF-Slim训练自己的数据，并用来对图片进行分类，看了您的代码，发现您一直用的是pretrain的模型，我不太清楚用自己的模型，自己的标签label应该怎么做？
希望获得您的指导
